name: Config Cron Job

on:
  schedule:
    - cron: '5 0 * * *'  # Chạy lúc 0h05 mỗi ngày
  workflow_dispatch:      # Cho phép chạy thủ công nếu cần

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Amazon Corretto 18.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Kotlin Main
        run: |
          export CONFIG_URL='${{ secrets.S_CONFIG_URL }}'
          ./gradlew run

      - name: Check and commit if changes
        id: check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Update output at $(date)"
            git push origin main
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
